language: smalltalk
services:
- docker
env:
  jobs:
  - SQUEAK_VERSION=Trunk
  - SQUEAK_VERSION=5.3
smalltalk: "Squeak64-${SQUEAK_VERSION}"

before_script:
- chmod +x travis_fold
- |
  # DEBUG_FIGURES allows PDF builds despite missing figures
  export DEBUG_FIGURES=true && [ "$TRAVIS_BRANCH" = "master" ] && export DEBUG_FIGURES=false ; :
- set -o pipefail

script:
- smalltalkci .smalltalk.ston
- make | ./travis_fold Compiling PDF ...
- mv SBE.pdf "SBE_${SQUEAK_VERSION}.pdf"

after_script:
- | # Upload PDF file to Google Drive
  if [ -f "SBE_${SQUEAK_VERSION}.pdf" ] && [ "$TRAVIS_PULL_REQUEST" = false ]
  then
    bash -e deploy-debug.sh "SBE_${SQUEAK_VERSION}.pdf"
  fi

deploy:
  - # Create GitHub release
    provider: releases
    on:
      branch: master
    file: "SBE_{SQUEAK_VERSION}.pdf"
    api_key:
      secure: E1hGhzyqbVZ5oHOYfOUlyrFY6GQ87+QI4Ow7d70bNMcJozTgeHw08Fq9i0Xx1uXKi7eR5UwyAiHzbBqw/nAqiJZqJyVm9DgYtdMwgjx8zx0eb3tUS7ADlM5mloKCyIMyxo7SyeEkWMGC9gpsiQ8o2nACV81r/nnWm8+ZCu+H8fEJctaPx7DtyP4l3Mg5THGJs5ioYfGDRuxdg2Ct7BXb76+59sHN5Wxw56GKJ88xU5JsAuV8lud5gKaxNzsjTo+l6zF9VmxM3rhvVmagg2o6pM5Hi7Dj66qJcg/klyMa0UaK6mjL5iVQuw6cP+izM78z5/CJY/PGu1WXQ0GqU3NMqJA52CgF4YwEItlHZAa/PDpHV7pCAyiJpSNbnkeUOV3W4vgBAXlLIdl5WISoW1GDH3hcxNY2ZIxqW8YwYBcFKG+GI/eUI9d3z8AHYch08QrmRkl2WAMx2BMXWn47mYgm0+720dqaE/TbTQPzJgAHTVKP39qhlonW24ABU14U6koaRk2PD5TeKRym8jxgJzH/BfQzCQ5pMGwuLgEJP6ckWQLFTCqeCjKhjIFUxFIhyY3EUjKDHN5N+PwCslEZRkPpR8nN3w3uW18qJIWfSOtPbCmS+dbGXdvHtWQaSuVYy4bVyRqQkNfyPpvRCiJtyQZTTegARGrTNBtbtnN3V9vzZyQ=
    cleanup: false

notifications:
  email:
    if: type = cron
