env:
  - SQUEAK_VERSION=Trunk
  - SQUEAK_VERSION=5.3

language: smalltalk
services:
- docker
smalltalk: "Squeak64-${SQUEAK_VERSION}"

before_script:
- | # Ignore missing figures during PDF build
  test $TRAVIS_BRANCH = master || DEBUG_FIGURES=true
- set -o pipefail
script:
- echo "<build>" # DEBUG!
#- smalltalkci .smalltalk.ston
#- make | ./travis_fold Compiling PDF ...
#- mv SBE.pdf "SBE_${SQUEAK_VERSION}.pdf"
after_script:
- | # Upload PDF file to Google Drive
  # It would be nicer to have a deploy job for this, but Travis seems
  # not to support this ATM. See also:
  # 46e4347fea190aeb9abab05f27764bee7c8ae871
  if [ -f "SBE_${SQUEAK_VERSION}.pdf" ] && [ "$TRAVIS_PULL_REQUEST" = false ]
  then
    bash -e deploy-debug.sh "SBE_${SQUEAK_VERSION}.pdf"
  fi

jobs:
  include:
    - stage: deploy
      env: SQUEAK_VERSION=
      language: minimal
      install: skip
      script: true
      deploy: # Create GitHub release
        provider: releases
        file: "SBE_*.pdf"
        api_key: $GH_OAUTH_TOKEN
        cleanup: false
      on:
        branch: master

notifications:
  email:
    if: type = cron
