env:
  - SQUEAK_VERSION=Trunk
  - SQUEAK_VERSION=5.3

language: smalltalk
services:
- docker
smalltalk: "Squeak64-${SQUEAK_VERSION}"

before_script:
- | # Ignore missing figures during PDF build
  test $TRAVIS_BRANCH = master || DEBUG_FIGURES=true
- set -o pipefail
script:
- smalltalkci .smalltalk.ston
- make | ./travis_fold Compiling PDF ...
- mv SBE.pdf "SBE_${SQUEAK_VERSION}.pdf"
after_script: test -f "SBE_${SQUEAK_VERSION}.pdf" && SBE_gdrive_upload.sh "SBE_${SQUEAK_VERSION}.pdf"

jobs:
  include:
    - stage: deploy
      #if: branch = master AND type = push # DEBUG
      name: GitHub Release
      env: SQUEAK_VERSION=
      language: minimal
      install: skip
      script: true
      deploy:
        provider: releases
        file: "SBE_*.pdf"
        api_key: $GH_OAUTH_TOKEN
        cleanup: false
      #on:
      #  branch: master
      # DEBUG

notifications:
  email:
    if: type = cron
