env:
  - SQUEAK_VERSION=Trunk
  - SQUEAK_VERSION=5.3

language: smalltalk
services:
- docker
smalltalk: "Squeak64-${SQUEAK_VERSION}"

before_script:
- | # Ignore missing figures during PDF build
  test $TRAVIS_BRANCH = master || export DEBUG_FIGURES=true
- set -o pipefail
script:
- #smalltalkci .smalltalk.ston DEBUG
- make | ./travis_fold Compiling PDF ...
- mv SBE.pdf "SBE_${SQUEAK_VERSION}.pdf"
after_script: test "$TRAVIS_BRANCH" = "master" && gdrive_upload.sh "SBE_${SQUEAK_VERSION}.pdf"

jobs:
  include:
    - stage: deploy
      #if: branch = master AND type = push # DEBUG
      name: GitHub Release
      env: SQUEAK_VERSION=
      language: minimal
      install: skip
      script: ls "SBE_*.pdf" # DEBUG
      deploy:
        provider: releases
        file: "SBE_*.pdf"
        api_key: $GH_OAUTH_TOKEN
        cleanup: false
        on:
          all_branches: true

notifications:
  email:
    if: type = cron
